# Generated by Django 4.2 on 2023-06-19 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("description", models.CharField(blank=True, max_length=150)),
                ("url", models.SlugField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_name", models.CharField(max_length=50)),
                ("max_deposits", models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name="Deposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("deposited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "box_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="box_management.box",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_id", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=50)),
                ("artist", models.CharField(max_length=50)),
                ("url", models.URLField()),
                ("image_url", models.URLField(blank=True)),
                ("duration", models.IntegerField(default=0)),
                ("platform_id", models.IntegerField(default=0)),
                ("n_deposits", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="VisibleDeposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deposit_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="box_management.deposit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LocationPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("dist_location", models.IntegerField(default=100)),
                (
                    "box_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="box_management.box",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="deposit",
            name="song_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="box_management.song"
            ),
        ),
    ]
