# Generated by Django 4.2 on 2023-06-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song", name="song_id", field=models.CharField(max_length=15),
        ),
    ]
