# Generated by Django 4.2 on 2023-06-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="box", name="client_name", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="box", name="latitude", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="box", name="longitude", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="box", name="url", field=models.SlugField(blank=True),
        ),
    ]
