# Generated by Django 4.2.1 on 2023-06-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box_management", "0002_alter_box_client_name_alter_box_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="box",
            name="dist_location",
            field=models.IntegerField(default=100),
        ),
    ]
