# Generated by Django 4.2 on 2023-06-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box_management", "0002_song_duration_song_n_platform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song", name="duration", field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="song", name="n_platform", field=models.IntegerField(default=0),
        ),
    ]
