# Generated by Django 4.2 on 2023-06-08 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("box_management", "0003_alter_song_duration_alter_song_n_platform"),
    ]

    operations = [
        migrations.RenameField(
            model_name="song", old_name="n_platform", new_name="platform_id",
        ),
    ]
