# Generated by Django 4.2.1 on 2023-06-15 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("box_management", "0003_box_dist_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="box",
            name="dist_location",
        ),
        migrations.RemoveField(
            model_name="box",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="box",
            name="longitude",
        ),
        migrations.CreateModel(
            name="LocalisationPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("latitude", models.CharField(max_length=50)),
                ("longitude", models.CharField(max_length=50)),
                ("dist_location", models.IntegerField(default=100)),
                (
                    "box_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="box_management.box",
                    ),
                ),
            ],
        ),
    ]
