# Generated by Django 4.2 on 2023-06-15 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "box_management",
            "0004_remove_box_dist_location_remove_box_latitude_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(old_name="LocalisationPoint", new_name="LocationPoint",),
    ]
