# Generated by Django 4.2.2 on 2023-06-20 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box_management', '0004_deposit_note'),
        ('box_management', '0004_discoveredsong'),
    ]

    operations = [
    ]
