# Generated by Django 4.2.2 on 2023-06-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box_management', '0005_rename_localisationpoint_locationpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='deposited_at',
            field=models.DateTimeField(),
        ),
    ]
