# Generated by Django 4.2 on 2023-06-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box_management", "0005_alter_box_client_name_alter_box_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="box", name="latitude", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="box", name="longitude", field=models.CharField(max_length=50),
        ),
    ]
