# Generated by Django 4.2 on 2023-06-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box_management", "0005_rename_localisationpoint_locationpoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="box", name="max_deposit", field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="locationpoint", name="latitude", field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="locationpoint", name="longitude", field=models.FloatField(),
        ),
    ]
