# Generated by Django 4.2.1 on 2023-06-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box_management", "0006_alter_locationpoint_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="max_deposits",
            field=models.IntegerField(default=5),
        ),
    ]
