# Generated by Django 4.2.1 on 2023-06-15 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("box_management", "0007_rename_max_deposit_box_max_deposits"),
        ("box_management", "0007_song_max_deposits"),
    ]

    operations = []
