# Generated by Django 5.0.4 on 2024-05-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box_management", "0007_alter_locationpoint_latitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposit",
            name="is_visible",
            field=models.BooleanField(default=False),
        ),
    ]
