# Generated by Django 5.0.4 on 2024-05-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box_management", "0008_deposit_is_visible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposit",
            name="note",
            field=models.CharField(
                blank=True,
                choices=[
                    ("calme", "Cette chanson m'apaise et me détend !"),
                    ("danse", "Cette chanson me donne envie de danser !"),
                    ("inspire", "Cette chanson me pousse à être créatif !"),
                    ("joie", "Cette chanson me met de bonne humeur !"),
                    ("motive", "Cette chanson me motive pour la journée !"),
                    ("reflexion", "Cette chanson me fait réfléchir sur la vie."),
                    ("rire", "Cette chanson me fait rire !"),
                    ("triste", "Cette chanson me rend mélancolique !"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
