# Generated by Django 4.2.1 on 2023-06-15 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("box_management", "0008_merge_20230615_1535"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="max_deposits",
        ),
    ]
