# Generated by Django 4.2.1 on 2023-06-16 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("box_management", "0009_remove_song_max_deposits"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisibleDeposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deposit_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="box_management.deposit",
                    ),
                ),
            ],
        ),
    ]
