# Generated by Django 5.0.4 on 2024-06-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box_management", "0009_alter_deposit_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="song_id",
            field=models.CharField(max_length=50),
        ),
    ]
