# Generated by Django 5.0.4 on 2024-06-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box_management", "0010_alter_song_song_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deposit",
            old_name="box_id",
            new_name="box",
        ),
        migrations.RenameField(
            model_name="deposit",
            old_name="song_id",
            new_name="song",
        ),
        migrations.AlterField(
            model_name="deposit",
            name="deposited_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
