# Generated by Django 5.0.4 on 2024-06-08 11:04

import box_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box_management", "0011_rename_box_id_deposit_box_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="deezer_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[box_management.models.validate_spotify_or_deezer_id],
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="spotify_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[box_management.models.validate_spotify_or_deezer_id],
            ),
        ),
    ]
