# Generated by Django 5.0.4 on 2024-06-10 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("box_management", "0012_song_deezer_id_song_spotify_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="locationpoint",
            old_name="box_id",
            new_name="box",
        ),
    ]
