# Generated by Django 5.0.4 on 2024-06-11 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box_management", "0013_rename_box_id_locationpoint_box"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cardboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_url", models.SlugField(unique=True)),
                (
                    "box",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="box_management.box",
                    ),
                ),
            ],
        ),
    ]
