# Generated by Django 5.0.4 on 2024-06-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box_management", "0014_cardboard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposit",
            name="note",
            field=models.CharField(
                blank=True,
                choices=[
                    ("donnesourire", "Cette chanson me donne toujours le sourire"),
                    ("momentdejoie", "Cette chanson rappelle des moments de joie"),
                    ("souvenirfetes", "Cette chanson évoque des souvenirs de fêtes"),
                    ("faitdanser", "Cette chanson me fait toujours danser"),
                    (
                        "remplitbonheur",
                        "Cette chanson me remplit de bonheur instantanément",
                    ),
                    (
                        "remedejoursgris",
                        "Cette chanson est mon remède contre les jours gris",
                    ),
                    (
                        "joursheureuxenfance",
                        "Cette chanson rappelle les jours heureux de mon enfance",
                    ),
                    ("explosionjoie", "Cette chanson est une explosion de joie"),
                    (
                        "accompagnenostalgie",
                        "Cette chanson m'accompagne quand je suis nostalgique",
                    ),
                    (
                        "pleurerchaquefois",
                        "Cette chanson me fait pleurer à chaque fois",
                    ),
                    (
                        "nuitsdete",
                        "Cette chanson rappelle les nuits d'été sous les étoiles",
                    ),
                    (
                        "momentspasses",
                        "Cette chanson me fait revivre les moments passés",
                    ),
                    ("doucemelancolie", "Cette chanson évoque une douce mélancolie"),
                    ("pleinenostalgie", "Cette chanson est pleine de nostalgie"),
                    (
                        "espoirsjeunesse",
                        "Cette chanson rappelle les rêves et espoirs de ma jeunesse",
                    ),
                    (
                        "periodedifficile",
                        "Cette chanson a été ma bande-son pendant une période difficile",
                    ),
                    (
                        "traverserrupture",
                        "Cette chanson m'a aidé à traverser une rupture",
                    ),
                    (
                        "ecouteaulycee",
                        "Cette chanson, je l'écoutais en boucle au lycée",
                    ),
                    (
                        "defissurmontes",
                        "Cette chanson rappelle les défis que j'ai surmontés",
                    ),
                    ("momentcle", "Cette chanson est liée à un moment clé de ma vie"),
                    (
                        "reussitesexamens",
                        "Cette chanson rappelle des examens et réussites",
                    ),
                    (
                        "tournantcarriere",
                        "Cette chanson a marqué un tournant dans ma carrière",
                    ),
                    (
                        "momentscruciaux",
                        "Cette chanson était là lors des moments cruciaux",
                    ),
                    (
                        "ecoleprimaire",
                        "Cette chanson me rappelle mes jours d'école primaire",
                    ),
                    (
                        "souvenircollege",
                        "Cette chanson évoque les souvenirs du collège",
                    ),
                    (
                        "souvenirlycee",
                        "Cette chanson était un hit pendant mes années de lycée",
                    ),
                    (
                        "souveniruniversité",
                        "Cette chanson me rappelle mes années à l'université",
                    ),
                    (
                        "naissanceenfant",
                        "Cette chanson est spéciale car je l'écoutais à la naissance de mon enfant",
                    ),
                    (
                        "nuitsblanchesenfant",
                        "Cette chanson me rappelle les nuits blanches en tant que jeune parent",
                    ),
                    ("premieremploi", "Cette chanson me ramène à mon premier emploi"),
                    ("souvenirmariage", "Cette chanson évoque le jour de mon mariage"),
                    (
                        "anneesdorees",
                        "Cette chanson m'accompagne dans mes années dorées",
                    ),
                    ("souveniramies", "Cette chanson me fait penser à mes ami·e·s"),
                    ("souvenirparents", "Cette chanson me fait penser à mes parents"),
                    (
                        "souvenirgrandsparents",
                        "Cette chanson me fait penser à mes grands-parents",
                    ),
                    (
                        "souvenirfreresoeur",
                        "Cette chanson me fait penser à mon·mes frère/ma·mes sœurs",
                    ),
                    (
                        "souvenircousin",
                        "Cette chanson me fait penser à mon·ma·mes mes cousin·e·s",
                    ),
                    ("souvenirenfants", "Cette chanson me fait penser à mes enfants"),
                    (
                        "souvenircollegues",
                        "Cette chanson me fait penser à mon·ma·mes collègue·s",
                    ),
                    (
                        "souveniramisenfance",
                        "Cette chanson me fait penser à mes vieux amis d'enfance",
                    ),
                    (
                        "meilleuresvacances",
                        "Cette chanson me rappelle les meilleures vacances",
                    ),
                    ("eteplage", "Cette chanson m’évoque les étés à la plage"),
                    ("souvenirenfance", "Cette chanson rappelle mon enfance"),
                    (
                        "roadtripinoubliable",
                        "Cette chanson, je l’ai découverte pendant un road trip inoubliable",
                    ),
                    (
                        "couchersoleilplage",
                        "Cette chanson me fait penser aux couchers de soleil sur la plage",
                    ),
                    (
                        "bandesonexploration",
                        "Cette chanson était la bande-son de nos explorations",
                    ),
                    ("hymneliberte", "Cette chanson est un hymne à la liberté"),
                    ("evasion", "Cette chanson m'aide à m'évader"),
                    ("accompagnevoyage", "Cette chanson m'a accompagné en voyage"),
                    ("voler", "Cette chanson me fait sentir comme si je volais"),
                    ("souvenirsfete", "Cette chanson rappelle des fêtes inoubliables"),
                    (
                        "invitationaventure",
                        "Cette chanson est une invitation à l'aventure",
                    ),
                    (
                        "paysagemagnifiques",
                        "Cette chanson rappelle des paysages magnifiques",
                    ),
                    ("voyagelointain", "Cette chanson, est un voyage lointain"),
                    ("motivation", "Cette chanson me motive quand j'en ai besoin"),
                    (
                        "dansesansretenue",
                        "Cette chanson me donne envie de danser sans retenue",
                    ),
                    ("sentirpuissance", "Cette chanson me fait me sentir puissant"),
                    ("boost", "Cette chanson me booste quand il le faut"),
                    ("trouverenergie", "Cette chanson m'aide à trouver de l'énergie"),
                    ("inspirationautop", "Cette chanson m'inspire à être au top"),
                    (
                        "crideguerre",
                        "Cette chanson est mon cri de guerre avant un défi",
                    ),
                    (
                        "toutaccomplir",
                        "Cette chanson me rappelle que je peux tout accomplir",
                    ),
                    (
                        "briserchaines",
                        "Cette chanson m'inspire à briser toutes les chaînes",
                    ),
                    (
                        "rienimpossible",
                        "Cette chanson me fait sentir que rien n'est impossible",
                    ),
                    (
                        "donneespoir",
                        "Cette chanson, les paroles me donnent de l'espoir",
                    ),
                    (
                        "donnefrissons",
                        "Cette chanson me donne des frissons à chaque écoute",
                    ),
                    (
                        "transporteailleurs",
                        "Cette chanson me transporte instantanément ailleurs",
                    ),
                    ("parolesresonne", "Cette chanson, les paroles résonnent en moi"),
                    ("inspiremeilleur", "Cette chanson m'inspire à être meilleur"),
                    (
                        "toujoursespoir",
                        "Cette chanson rappelle qu'il y a toujours de l'espoir",
                    ),
                    (
                        "paroletoucher",
                        "Cette chanson, les paroles me touchent profondément",
                    ),
                    ("pourreflexion", "Cette chanson est parfaite pour la réflexion"),
                    ("pourmediter", "Cette chanson est idéale pour méditer"),
                    (
                        "momentcalme",
                        "Cette chanson est toujours là pour mes moments de calme",
                    ),
                    ("pourrecentrer", "Cette chanson m'apaise et me recentre"),
                    (
                        "sereniteinterieur",
                        "Cette chanson m'aide à trouver la sérénité intérieure",
                    ),
                    (
                        "pourcontemplation",
                        "Cette chanson est idéale pour la contemplation",
                    ),
                    (
                        "accompagnesolitude",
                        "Cette chanson m'accompagne dans la solitude",
                    ),
                    ("reflechir", "Cette chanson est mon refuge pour réfléchir"),
                    (
                        "promenadetranquille",
                        "Cette chanson est parfaite pour une promenade tranquille",
                    ),
                    (
                        "joursdepluie",
                        "Cette chanson est idéale pour les jours de pluie",
                    ),
                    (
                        "pouryoga",
                        "Cette chanson m'accompagne lors de mes séances de yoga",
                    ),
                    (
                        "bainrelaxant",
                        "Cette chanson est parfaite pour un bain relaxant",
                    ),
                    (
                        "endormirpaisiblement",
                        "Cette chanson est idéale pour s'endormir paisiblement",
                    ),
                    (
                        "longuejournee",
                        "Cette chanson m'aide à me détendre après une longue journée",
                    ),
                    (
                        "lecturetranquille",
                        "Cette chanson m'accompagne pendant mes lectures tranquilles",
                    ),
                    (
                        "pausedetentenature",
                        "Cette chanson est idéale pour une pause détente en pleine nature",
                    ),
                    (
                        "regarderetoiles",
                        "Cette chanson est parfaite pour écouter en regardant les étoiles",
                    ),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
