# Generated by Django 5.0.4 on 2024-06-17 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box_management", "0016_remove_song_n_deposits_remove_song_song_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="discoveredsong",
            old_name="deposit_id",
            new_name="deposit",
        ),
        migrations.RenameField(
            model_name="discoveredsong",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="deposit",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deposits",
                to="box_management.song",
            ),
        ),
    ]
