# Generated by Django 4.2.1 on 2023-06-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_platform',
            field=models.CharField(blank=True, choices=[('spotify', 'Spotify'), ('deezer', 'Deezer')], max_length=10),
        ),
    ]
