# Generated by Django 4.2 on 2023-06-13 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0002_remove_spotifytoken_user_spotifytoken_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="spotifytoken", old_name="user_id", new_name="user",
        ),
    ]
