# Generated by Django 4.2 on 2023-06-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MusicDeposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(max_length=15)),
                ("music_id", models.CharField(max_length=15)),
                ("time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
