# Generated by Django 4.1.7 on 2023-04-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='abcd', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='abcd', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
