# Generated by Django 4.1.7 on 2023-04-12 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_password_user_username_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
