# Generated by Django 4.1.7 on 2023-04-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_musicbox_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.CharField(default='test', max_length=15)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MusicBox',
        ),
    ]
