# Generated by Django 4.1.7 on 2023-04-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_musicdeposit_delete_musicbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicdeposit',
            name='host',
            field=models.CharField(default='test', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='musicdeposit',
            name='music_id',
            field=models.CharField(max_length=15),
        ),
    ]
