# Generated by Django 4.1.7 on 2023-04-25 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_musicdeposit_host_alter_musicdeposit_music_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicdeposit',
            name='host',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
