# Generated by Django 4.1.7 on 2023-04-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_musicdeposit_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicdeposit',
            name='host',
            field=models.CharField(max_length=15),
        ),
    ]
