# Generated by Django 4.2 on 2023-05-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Boites",
            fields=[
                ("id_boite", models.AutoField(primary_key=True, serialize=False)),
                ("nom_boite", models.CharField(max_length=50, unique=True)),
                ("url_image", models.CharField(max_length=150)),
                ("description_boite", models.CharField(max_length=150)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("location_lat", models.CharField(max_length=50, unique=True)),
                ("location_long", models.CharField(max_length=50, unique=True)),
                ("client", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Deposit",
            fields=[
                ("id_deposit", models.AutoField(primary_key=True, serialize=False)),
                ("id_song", models.IntegerField()),
                ("id_boite", models.IntegerField()),
                ("deposited_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                ("id_song", models.AutoField(primary_key=True, serialize=False)),
                ("name_song", models.CharField(max_length=50, unique=True)),
                ("name_artist", models.CharField(max_length=50, unique=True)),
                ("url_song", models.CharField(max_length=150)),
                ("url_image", models.CharField(max_length=150)),
                ("n_deposits", models.IntegerField(default=0)),
            ],
        ),
    ]
