# Generated by Django 4.2 on 2023-05-15 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_boites", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Boites", new_name="Box",),
    ]
