# Generated by Django 4.2 on 2023-05-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_boites", "0002_rename_boites_box"),
    ]

    operations = [
        migrations.AddField(
            model_name="box",
            name="url_box",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="box", name="url_image", field=models.URLField(),
        ),
    ]
