# Generated by Django 4.2 on 2023-05-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_boites", "0004_alter_song_url_image_alter_song_url_song"),
    ]

    operations = [
        migrations.AlterField(
            model_name="box",
            name="description_boite",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="box", name="url_image", field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="song",
            name="name_artist",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="song", name="name_song", field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="song", name="url_image", field=models.URLField(blank=True),
        ),
    ]
