# Generated by Django 4.2 on 2023-06-13 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("deezer", "0002_alter_deezertoken_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deezertoken", old_name="user", new_name="user_id",
        ),
    ]
