"""
Django settings for la_boite_a_son project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from spotify.credentials import CLIENT_ID, CLIENT_SECRET
from deezer.credentials import LOGIN_APP_ID, LOGIN_APP_SECRET

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(dotenv_path=BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mwb#$xb6cdl#+v*#7_r04r&d7dx#cn@lvhp)syyn-(84k87cvn'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['boiteachanson.fr', 'www.boiteachanson.fr', "musikmap.com", "www.musikmap.com" ,'46.202.175.139']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'import_export',
    'django.contrib.staticfiles',
    'frontend.apps.FrontendConfig',
    'rest_framework',
    'django_extensions',
    'spotify.apps.SpotifyConfig',
    'deezer.apps.DeezerConfig',
    'box_management.apps.BoxManagementConfig',
    'users',

    # Django Social-Auth
    'social_django'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Django Social-Auth middleware
    'social_django.middleware.SocialAuthExceptionMiddleware'
]

ROOT_URLCONF = 'la_boite_a_son.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "frontend/templates/frontend"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # Django Social-Auth processors
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect'
            ],
        },
    },
]

# Authentication providers
# https://python-social-auth.readthedocs.io/en/latest/configuration/django.html
AUTHENTICATION_BACKENDS = [

    # Music streaming platforms
    'social_core.backends.spotify.SpotifyOAuth2',
    'social_core.backends.deezer.DeezerOAuth2',

    # Default auth model
    'django.contrib.auth.backends.ModelBackend',
]

WSGI_APPLICATION = 'la_boite_a_son.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', default='localhost'),
        'PORT': os.getenv('DB_PORT', default='5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'Europe/Paris'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = Path("/var/www/boite-a-groove/static")

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Define media URL for user.profile_picture.url
MEDIA_URL = '/media/'

# Make folder accessible in static
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# General Social-Auth settings
# https://python-social-auth.readthedocs.io/en/latest/configuration/django.html

AUTH_USER_MODEL = 'users.CustomUser'
SOCIAL_AUTH_USER_MODEL = 'users.CustomUser'
LOGIN_REDIRECT_URL = '/profile'

# Social-Auth settings for Spotify provider
# https://python-social-auth.readthedocs.io/en/latest/backends/spotify.html

SOCIAL_AUTH_SPOTIFY_KEY = CLIENT_ID
SOCIAL_AUTH_SPOTIFY_SECRET = CLIENT_SECRET
SOCIAL_AUTH_SPOTIFY_SCOPE = ['user-read-email']
SOCIAL_AUTH_SPOTIFY_EXTRA_DATA = [('email', 'email')]

# Social-Auth settings for Deezer provider

SOCIAL_AUTH_DEEZER_KEY = LOGIN_APP_ID
SOCIAL_AUTH_DEEZER_SECRET = LOGIN_APP_SECRET
SOCIAL_AUTH_DEEZER_SCOPE = ['user-read-email']
SOCIAL_AUTH_DEEZER_EXTRA_DATA = [('email', 'email')]



